apiVersion: v1
kind: Pod
metadata:
  name: kube-sender
spec:
  serviceAccountName: kube-metrics
  containers:
    - name: kube-sender
      image: kube-metric:test
      env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: "<someappinsightsvalue>"
