apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-metrics
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: hpa-reader
  namespace: default
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "autoscaling" ]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: [ "horizontalpodautoscalers" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: read-hpa-global
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kube-metrics # Name is case sensitive
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: hpa-reader
  apiGroup: rbac.authorization.k8s.io
